### ISSUE TITLE
Invalid interaction application command

### ISSUE THREAD

**Issue by BenitzCoding** [TricolorHen061/discordpy-slash#1]
![image](https://user-images.githubusercontent.com/70798458/112753517-5f6d3f80-900a-11eb-8d71-04ceb6dc435d.png)
I have the command coded in my bot, but it doesn't work.

**Comment by TricolorHen061** [comment]
Oh, thanks for opening an issue on this. This is a client issue. It means your client doesn't have the up to date command list for your bot. Just run the command again or if that doesn't work, press ctrl + r in while you're in Discord.

**Comment by BenitzCoding** [comment]
The bot has synced the command, and I have restarted discord as well. I still can't get it to work.

**Comment by BenitzCoding** [comment]
Ok, I've got it to work somehow, but how do I do the command descriptions, choice descriptions, remove the "`self`" option in cog commands, and optional choices?

**Comment by TricolorHen061** [comment]
To add descriptions, use the `description` parameter in the `bot.command()` decorator. I will release an update today that gives you the option to add command choices and automatically remove the `self` parameter. I will make another comment on this issue when I do release the update.

**Comment by TricolorHen061** [comment]
I have released the update. Make sure you update with pip. To add choices to commands, look at the new `choices` parameter in the README.md file. When you run the command, it might give you the `Invalid interaction application command`, just keep running it until it works.
