### ISSUE TITLE
No Embed support

### ISSUE THREAD

**Issue by NekoMimiOfficial** [TricolorHen061/discordpy-slash#2]
Howdy 

i've tried to use this with my existing commands
all normal commands that dont output in an embed work however when i run a commands the outputs in an embed it sends an error for some of them
please note that these embeds contain images / emojis

i've tried it on an embed that uses just text and it works

Object of type Embed is not JSON serializable

also i would like to ask , is there a way we can define only some commands to load and not all

thanks in advance

**Comment by NekoMimiOfficial** [comment]
i would like to add , i know the issue is because of it sending non text objects , but what could be done to solve this since we cant set_image without it sending an image

**Comment by NekoMimiOfficial** [comment]
also ive tried to send a local saved image in an embed and this is the output

send() got an unexpected keyword argument 'file'

**Comment by TricolorHen061** [comment]
@lilBigDev For the first problem you explained, can you please provide the full error with traceback? I'll see what I can do. The second problem you talked about is because this library doesn't support media yet. I'll definitely implement support for media and update you when it's complete. My discord account is TricolorHen061#1443 if you'd like to DM me.

**Comment by NekoMimiOfficial** [comment]
well i should have titled this issue No Image in embed support
i believe i said embeds with text only do work

assuming the second issue you mean is images (media) then thats the only thing
as i said the error that i get when i use an embed with set_image is
Object of type Embed is not JSON serializable

and when i try to send a local image by sending a file and using url="attachment://" in set_image i get
send() got an unexpected keyword argument 'file'

this is an example of a local image in an embed


```
@commands.command()
    @commands.guild_only()
    async def slap(self,ctx,usr:discord.Member=None):
        if usr == None:
            usr = ctx.author
        file = discord.File("emotes/slap.gif")
        e = discord.Embed(color=0xEE90AC,title='OUCHIE !')
        e.set_image(url="attachment://slap.gif")
        e.set_footer(text=f'{ctx.author.name} has slapped {usr.name} !')
        await ctx.send(file = file, embed=e)
```

as far as i've tested i never got any other error 

i hope this is enough info
also if you'd like to get faster responses or more flexibility my discord account is NekoMimi#0001
there are 3 zeros but github isnt loading them , thats NekoMimi# zero zero zero one

**Comment by TricolorHen061** [comment]
Sent a friend request

**Comment by NekoMimiOfficial** [comment]
issue was discussed and the culprit was a missing check for if the title in embeds were present
