### ISSUE TITLE
hidden_commands and Buttons not working.

### ISSUE THREAD

**Issue by zenfty** [TricolorHen061/discordpy-slash#3]
Hi, I was using hidden_commands to hide some commands from being shown on slash, and when I add hidden_commands to my code in the form of
```
await sync_all_commands(
        client=clt,
        loading_message='delta is processing...',
        hidden_commands=['prefix','shutdown','restart'],
        case_sensitive=False
    )
```
it simply doesn't remove the commands after finishing syncing.

And the buttons just return `Command raised an exception: TypeError: Messageable.send() got an unexpected keyword argument 'buttons'` when they are used like this:
```
await ctx.send(embed=emb,buttons=
        [
            Button(label='test1'),
            Button(label='test2')
        ])
```
Any help would be greatly appreciated, thank you so much, this has been a lifesaver.

**Comment by TricolorHen061** [comment]
Hey, thanks for using this library. Can you please DM me on Discord? TricolorHen061#1443

**Comment by zenfty** [comment]
Sent a request.

**Comment by TricolorHen061** [comment]
To anyone that may be reading this: We discussed, and he found another library to use.

Please note that this library is not meant to be used as a permanent solution. Rather, this is a hacky, temporary fix that should be used while you actually rewrite your bot to use slash commands.
